//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherNow.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public string Name { get; set; }
        public string Lat { get; set; }
        public string Lot { get; set; }
        public int ID { get; set; }
    }
}
